### ISSUE TITLE
Issue in the Flight Page

### ISSUE THREAD

**Issue by DhairyaPatel2210** [Harsh251299/WPL#4]
Situation: When we click on the search button without adding any passengers, we cannot submit the form. From the description below, I think it is not necessary to have passengers to submit the form. And even if it is necessary, every category should not be required. 

<img width="650" alt="image" src="https://github.com/user-attachments/assets/49a9ca2d-ecdf-49b4-a78a-92353debe73d">

**Comment by Harsh251299** [comment]
Implemented already
